# qmexport.py - module for migrating BBN data generated by Quote Master
#  to CSV format usable by Epicor ERP's DMT
from qmexport import config, load_data, map_data

# get the data
# for now, by opening a CSV of the result set of the queries
part_filename = config.csv_path + config.csv_files['part']
part_data = load_data.qm_read(format='csv', filename=part_filename)

# map QM values to fields expected by DMT, scrubbing & 
#  reformatting as necessary
dmt_part_data = map_data.map_part(part_data)

# export the Epicor-friendly data

# debugging info
print(len(part_data))
print(part_data[0])

print('\n')

print(len(dmt_part_data))
print(dmt_part_data[0])

counts = {}
for i in dmt_part_data:
    counts[i['ClassID']] = counts.get(i['ClassID'], 0) + 1
print(counts)

asbl_counts = {'-1': 0, '0': 0}
for i in part_data:
    asbl_counts[i['NRCCPrint']] += 1
print(asbl_counts)
